### ISSUE TITLE
Cannot simply "launch the app and play with it"

### ISSUE THREAD

**Issue by jazmatician** [Azure-Samples/active-directory-dotnet-native-uwp-wam#5]
The Readme says in "step 1" that we can "simply launch the app and play with it" in Visual Studio 2017. However, it doesn't seem to know the entry point. What's odd is that there's asolution file, but there doesn't appear to be any project files. I was unable to "Set Startup Item" on any of the files or pages. I was directed here as a "console" app, but it doesn't appear to be any kind of console app I've ever used.

Also, there is a Step 1, and [OPTIONAL] Step 2 with what looks like a bunch of substeps and then Step 4. Can someone please give this app and its documentation another look? Coming from a world where my connection string was basically "AuthType=AD" this is all very confusing.

**Comment by jmprieur** [comment]
@kalyankrishna1 see ... :)
