### ISSUE TITLE
Is there an inbuilt Logger available?

### ISSUE THREAD

**Issue by Druffl3** [Azure-Samples/active-directory-dotnet-native-uwp-wam#6]
I have set up the WAM integration based on the sample. The RequireTokenAsync method returns a ProviderError status. I would like to know more about what is going on? So, that I can fix this issue.

**Comment by jmprieur** [comment]
@bgavrilMS : would you know who to ask in the WAM team?

**Comment by Druffl3** [comment]
Hey @jmprieur , you and @bgavrilMS actually helped me resolve the issue here [1709](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1709). And bogdan had [responded](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1709#issuecomment-669901004) by saying that WAM is a windows component and  wouldn't know if it came with a logger. You can proceed to close this issue. Thank you.

**Comment by jmprieur** [comment]
Thanks for the update @Druffl3
